### ISSUE TITLE
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 7254

### ISSUE THREAD

**Issue by Bluscream** [SteamRE/DepotDownloader#131]
```
>dotnet DepotDownloader.dll -app 514900 -depot 514901 -manifest 7476077182338672655 -username xxx -password xxx
Connecting to Steam3... Done!
Logging 'xxx' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter your 2 factor auth code from your authenticator app: xxx
Retrying Steam3 connection... Done!
Logging 'xxx' into Steam3... Done!
Using Steam3 suggested CellID: 5
Got 11356 licenses for account!
Got session token!
Got Machine Auth: ssfn1692509040987900641 0 2048 2048
Got AppInfo for 514900
Accepted new login key for account xxx
Got 11356 licenses for account!
Download failed to due to an unhandled exception: An item with the same key has already been added. Key: 7254
Disconnected from Steam
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 7254
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at DepotDownloader.Steam3Session.LicenseListCallback(LicenseListCallback licenseList) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 648
   at SteamKit2.Internal.Callback`1.Run(Object callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr_Internals.cs:line 81
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 142
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.Handle(ICallbackMsg call) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 143
   at SteamKit2.CallbackManager.RunWaitCallbacks(TimeSpan timeout) in C:\Projects\SteamKit\SteamKit2\SteamKit2\Steam\SteamClient\CallbackMgr\CallbackMgr.cs:line 71
   at DepotDownloader.Steam3Session.WaitForCallbacks() in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 495
   at DepotDownloader.Steam3Session.WaitUntilCallback(Action submitter, WaitCondition waiter) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 143
   at DepotDownloader.Steam3Session.RequestPackageInfo(IEnumerable`1 packageIds) in C:\Projects\DepotDownloader\DepotDownloader\Steam3Session.cs:line 260
   at DepotDownloader.ContentDownloader.AccountHasAccess(UInt32 depotId) in C:\Projects\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 129
   at DepotDownloader.ContentDownloader.DownloadAppAsync(UInt32 appId, UInt32 depotId, UInt64 manifestId, String branch, String os, String arch, String language, Boolean lv, Boolean isUgc) in C:\Projects\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 412
   at DepotDownloader.Program.MainAsync(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 213
   at DepotDownloader.Program.Main(String[] args) in C:\Projects\DepotDownloader\DepotDownloader\Program.cs:line 14
```

**Comment by azuisleet** [comment]
This should be fixed on master, https://github.com/SteamRE/DepotDownloader/commit/4c36d5ca31ffe6294be768c4c89a3c862ce3dcc0

You can either build and run from source, or this will be in the next release.

**Comment by Bluscream** [comment]
Thanks, ill leave this open until the release is out ^^

**Comment by Bluscream** [comment]
Is the release out @?

**Comment by Luckz** [comment]
> Is the release out?

Seems you helped trigger one, https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.0
Fixes it for me.
