### ISSUE TITLE
[CDNClient] Failed to complete web request and Connection timeout downloading chunk

### ISSUE THREAD

**Issue by SharlLegreg** [SteamRE/DepotDownloader#176]
```PS C:\Users\USER\Downloads\depotdownloader-2.4.0-prerelease> dotnet DepotDownloader.dll -app 730 -depot 731 -manifest 3142397774332541273 -username [REDACTED] -password [REDACTED] -debug
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
[ServerList] Resolved 200 servers
[ServerList] Next server candidate: 103.10.124.163:27021 (Tcp)
[faa028fab1344ea5b2c16c5d65341bf8/TcpConnection] Connecting to 103.10.124.163:27021...
[faa028fab1344ea5b2c16c5d65341bf8/TcpConnection] Connected to 103.10.124.163:27021
[faa028fab1344ea5b2c16c5d65341bf8/EnvelopeEncryptedConnection] Got encryption request. Universe: Public Protocol ver: 1
[faa028fab1344ea5b2c16c5d65341bf8/EnvelopeEncryptedConnection] Encryption result: OK
 Done!
Logging '[REDACTED]' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter your 2 factor auth code from your authenticator app: [faa028fab1344ea5b2c16c5d65341bf8/TcpConnection] Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\SteamKit2\Networking\Steam3\TcpConnection.cs:line 284
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\SteamKit2\Networking\Steam3\TcpConnection.cs:line 289
   at SteamKit2.TcpConnection.NetLoop() in C:\Projects\SteamKit\SteamKit2\SteamKit2\Networking\Steam3\TcpConnection.cs:line 247
[REDACTED]
Retrying Steam3 connection...[ServerList] Next server candidate: 103.10.124.163:27021 (Tcp)
[faa028fab1344ea5b2c16c5d65341bf8/TcpConnection] Connecting to 103.10.124.163:27021...
[faa028fab1344ea5b2c16c5d65341bf8/TcpConnection] Connected to 103.10.124.163:27021
[faa028fab1344ea5b2c16c5d65341bf8/EnvelopeEncryptedConnection] Got encryption request. Universe: Public Protocol ver: 1
[faa028fab1344ea5b2c16c5d65341bf8/EnvelopeEncryptedConnection] Encryption result: OK
 Done!
Logging '[REDACTED]' into Steam3... Done!
Using Steam3 suggested CellID: 72
Got 23 licenses for account!
Got session token!
Got AppInfo for 730
Accepted new login key for account [REDACTED]
Using app branch: 'Public'.
Got depot key for 731 result: OK
Processing depot 731 - Counter-Strike Global Offensive Beta Common
Already have manifest 3142397774332541273 for depot 731.
Manifest 3142397774332541273 (23/10/2013 11:19:31 PM)
Downloading depot 731 - Counter-Strike Global Offensive Beta Common

A billion lines of validating depot files 

Got CDN auth token for steam.apac.qtlglb.com result: OK (expires 21/2/2021 4:35:42 PM)
Got CDN auth token for steamcontent.com result: OK (expires 21/2/2021 4:35:43 PM)
Got CDN auth token for steampipe.akamaized.net result: OK (expires 21/2/2021 4:35:44 PM)
Got CDN auth token for f3b7q2p3.ssl.hwcdn.net result: OK (expires 21/2/2021 4:35:45 PM)
Got CDN auth token for steampipe.steamcontent.com result: OK (expires 21/2/2021 4:35:45 PM)
[CDNClient] Failed to complete web request to http://cache2-hkg1.steamcontent.com/depot/731/chunk/4c20ea582c319953ac88849b00639b1bf91565df: The operation was canceled.
[CDNClient] Failed to complete web request to http://cache10-sgp1.steamcontent.com/depot/731/chunk/cc8a484396fb0d075f400721d52a30f442094809: The operation was canceled.
Connection timeout downloading chunk 4c20ea582c319953ac88849b00639b1bf91565df
Connection timeout downloading chunk cc8a484396fb0d075f400721d52a30f442094809
[CDNClient] Failed to complete web request to https://google.cdn.steampipe.steamcontent.com/depot/731/chunk/a46e9988f92a7a0653968ec2cd59e3457f2d0a9e: The operation was canceled.
[CDNClient] Failed to complete web request to https://steampipe.akamaized.net/depot/731/chunk/ece1ec07cf1482c378c48c441bd5ae64d5b1a5a6: The operation was canceled.
Connection timeout downloading chunk a46e9988f92a7a0653968ec2cd59e3457f2d0a9e
Connection timeout downloading chunk ece1ec07cf1482c378c48c441bd5ae64d5b1a5a6
[CDNClient] Failed to complete web request to http://cache2-hkg1.steamcontent.com/depot/731/chunk/016dbf59c00073dd5cae3701547036b14141713e: The operation was canceled.
Connection timeout downloading chunk 016dbf59c00073dd5cae3701547036b14141713e
[CDNClient] Failed to complete web request to https://google.cdn.steampipe.steamcontent.com/depot/731/chunk/2ba4d24bff0eaef1c6ffb4846efba86ce94f6be6: The operation was canceled.
Connection timeout downloading chunk 2ba4d24bff0eaef1c6ffb4846efba86ce94f6be6
[CDNClient] Failed to complete web request to https://f3b7q2p3.ssl.hwcdn.net/depot/731/chunk/376ed0ee9ab76fe2e5243af7c58d05563f3d28bf: The operation was canceled.
Failed to find any server with chunk 376ed0ee9ab76fe2e5243af7c58d05563f3d28bf for depot 731. Aborting.
App 730 was not completely downloaded.
The operation was canceled.
[CDNClient] Failed to complete web request to http://steam.apac.qtlglb.com/depot/731/chunk/bdf9fec0b1ef9c3a9d4790672aec3050ce0e6c8b: The operation was canceled.
Connection timeout downloading chunk bdf9fec0b1ef9c3a9d4790672aec3050ce0e6c8b
[CDNClient] Failed to complete web request to https://steampipe.akamaized.net/depot/731/chunk/4c20ea582c319953ac88849b00639b1bf91565df: The operation was canceled.
[CDNClient] Failed to complete web request to http://steam.apac.qtlglb.com/depot/731/chunk/cc8a484396fb0d075f400721d52a30f442094809: The operation was canceled.
Connection timeout downloading chunk 4c20ea582c319953ac88849b00639b1bf91565df
Connection timeout downloading chunk cc8a484396fb0d075f400721d52a30f442094809
[CDNClient] Failed to complete web request to http://cache1-sgp1.steamcontent.com/depot/731/chunk/ece1ec07cf1482c378c48c441bd5ae64d5b1a5a6: The operation was canceled.
[CDNClient] Failed to complete web request to https://f3b7q2p3.ssl.hwcdn.net/depot/731/chunk/a46e9988f92a7a0653968ec2cd59e3457f2d0a9e: The operation was canceled.
Connection timeout downloading chunk ece1ec07cf1482c378c48c441bd5ae64d5b1a5a6
Failed to find any server with chunk a46e9988f92a7a0653968ec2cd59e3457f2d0a9e for depot 731. Aborting.
[CDNClient] Failed to complete web request to http://cache4-hkg1.steamcontent.com/depot/731/chunk/016dbf59c00073dd5cae3701547036b14141713e: The operation was canceled.
Connection timeout downloading chunk 016dbf59c00073dd5cae3701547036b14141713e
[CDNClient] Failed to complete web request to http://cache2-hkg1.steamcontent.com/depot/731/chunk/2ba4d24bff0eaef1c6ffb4846efba86ce94f6be6: The operation was canceled.
Connection timeout downloading chunk 2ba4d24bff0eaef1c6ffb4846efba86ce94f6be6
Failed to retrieve content server list: The operation was canceled.
Disconnected from Steam```

How to fix this? It always comes up after 1-2 files have downloaded.

**Comment by SharlLegreg** [comment]
Using .NET Core 5.01 on Windows 10 through Powershell

**Comment by antel** [comment]
> Using .NET Core 5.01 on Windows 10 through Powershell

same error, tried with dotnet 3 & latest 5

**Comment by azuisleet** [comment]
Can you confirm if this is happening on the 2.4.0 pre-release? 
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.0

**Comment by antel** [comment]
> Can you confirm if this is happening on the 2.4.0 pre-release?
> https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.0

Yes can confirm, tried also -max-servers 1, if I can do any debug tell me, I got VS2019
command: dotnet.exe depotdownloader.dll -app 244930 -depot 244932 -manifest 3196555988536815060 -username user -password pass

**Comment by azuisleet** [comment]
2.4.1 contains a revised timeout mechanism for downloads. Take a look and let me know if you still have download issues. https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.1
