### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by NicknineTheEagle** [SteamRE/DepotDownloader#188]
DepotDownloader fails with "The process cannot access the file because it is being used by another process." error when trying to download app 220. I believe this is happening due to same named files being present in multiple depots at once which messes with DepotDownloader's new parallel downloading system.
```
Unhandled Exception: System.IO.IOException: The process cannot access the file 'E:\Utilities\DepotDownloader\HL2\hl2\cfg\chapter10.cfg' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at DepotDownloader.ContentDownloader.DownloadSteam3AsyncDepotFile(CancellationTokenSource cts, DepotFilesData depotFilesData, FileData file, ConcurrentQueue`1 networkChunkQueue) in D:\Sources\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 1123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at DepotDownloader.ContentDownloader.<>c__DisplayClass33_1.<<DownloadSteam3AsyncDepotFiles>b__3>d.MoveNext() in D:\Sources\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 971
--- End of stack trace from previous location where exception was thrown ---
   at DepotDownloader.Util.InvokeAsync(IEnumerable`1 taskFactories, Int32 maxDegreeOfParallelism) in D:\Sources\DepotDownloader\DepotDownloader\Util.cs:line 165
   at DepotDownloader.ContentDownloader.DownloadSteam3AsyncDepotFiles(CancellationTokenSource cts, UInt32 appId, GlobalDownloadCounter downloadCounter, DepotFilesData depotFilesData, HashSet`1 allFileNamesAllDepots) in D:\Sources\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 975
   at DepotDownloader.ContentDownloader.DownloadSteam3Async(UInt32 appId, List`1 depots) in D:\Sources\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 723
   at DepotDownloader.ContentDownloader.DownloadAppAsync(UInt32 appId, List`1 depotManifestIds, String branch, String os, String arch, String language, Boolean lv, Boolean isUgc) in D:\Sources\DepotDownloader\DepotDownloader\ContentDownloader.cs:line 593
   at DepotDownloader.Program.MainAsync(String[] args) in D:\Sources\DepotDownloader\DepotDownloader\Program.cs:line 232
   at DepotDownloader.Program.Main(String[] args) in D:\Sources\DepotDownloader\DepotDownloader\Program.cs:line 16
```

**Comment by azuisleet** [comment]
Take a look at 6b05a3e. The last depot to reference a file path is the one that we will download.

**Comment by NicknineTheEagle** [comment]
Fix seems to work as it should, thanks.
