### ISSUE TITLE
Download failed to due to an unhandled exception: Too many open files

### ISSUE THREAD

**Issue by willemml** [SteamRE/DepotDownloader#240]
I cannot seem to download old versions of Terraria on macOS 11.5 because DepotDownloader opens too many files (I do not know how many it opens)... It crashes with the following error message:
```
~/Downloads/depotdownloader-2.4.3-hotfix1 
❯ dotnet DepotDownloader.dll -app 105600 -depot 105603 -manifest 2710438662153675420 -username wnuke3 -password MYPASSWORD
Connecting to Steam3... Done!
Logging 'wnuke3' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter your 2 factor auth code from your authenticator app: CODE1
Retrying Steam3 connection... Done!
Logging 'wnuke3' into Steam3... Done!
Using Steam3 suggested CellID: 94
Got 217 licenses for account!
Got session token!
Got AppInfo for 105600
Using app branch: 'Public'.
Got depot key for 105603 result: OK
Processing depot 105603 - TerrariaMac
Already have manifest 2710438662153675420 for depot 105603.
Manifest 2710438662153675420 (6/4/2020 7:44:15 PM)
Downloading depot 105603 - TerrariaMac
Validating depots/105603/6707058/Terraria.app/Contents/Info.plist
Validating depots/105603/6707058/Terraria.app/Contents/MacOS/Content/Fonts/Item_Stack.xnb

# [...] large amounts of text listing files that were validated and or pre-allocated removed here, 2 examples below and two above...

Validating depots/105603/6707058/Terraria.app/Contents/MacOS/Content/Images/Projectile_265.xnb
Validating depots/105603/6707058/Terraria.app/Contents/MacOS/Content/Images/Projectile_269.xnb
Download failed to due to an unhandled exception: Too many open files
Accepted new login key for account wnuke3
Unhandled exception. System.IO.IsolatedStorage.IsolatedStorageException: Operation not permitted on IsolatedStorageFileStream.
 ---> System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream.InitializeFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   --- End of inner exception stack trace ---
   at System.IO.IsolatedStorage.IsolatedStorageFileStream.InitializeFileStream(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(String path, FileMode mode, FileAccess access)
   at DepotDownloader.AccountSettingsStore.Save()
   at DepotDownloader.Steam3Session.LoginKeyCallback(LoginKeyCallback loginKey)
   at SteamKit2.Internal.Callback`1.Run(Object callback)
   at SteamKit2.CallbackManager.<>c__DisplayClass10_0.<Handle>b__1(CallbackBase callback)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SteamKit2.CallbackManager.RunWaitAllCallbacks(TimeSpan timeout)
   at DepotDownloader.Steam3Session.TryWaitForLoginKey()
   at DepotDownloader.ContentDownloader.ShutdownSteam3()
   at DepotDownloader.Program.MainAsync(String[] args)
   at DepotDownloader.Program.Main(String[] args)
zsh: abort      dotnet DepotDownloader.dll -app 105600 -depot 105603 -manifest  -username 
```

**Comment by willemml** [comment]
Note that I have also tried increasing the open file limit using various methods such as `ulimit -S -n 10240`, `sudo launchctl limit maxfiles 64000 524288` and some other that I cannot remember.

**Comment by willemml** [comment]
I decided to try an older release, https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.6 appears to work just fine.
Also, all tests I have done (newer and older versions) I have the following `dotnet`:
```
❯ dotnet --version
5.0.302
```

**Comment by xPaw** [comment]
Can you also test 2.4.1 and 2.4.2, that should help narrow it down a bit.

**Comment by azuisleet** [comment]
If this works in 2.3.6 but not 2.4, then it's likely this is a result of us holding *all* the file handles open. This can probably be solved by closing the file handles after validating, and then lazily re-opening them when it's time to download the chunks for that file.

**Comment by azuisleet** [comment]
I have a fix pending in bb778e3883f7d74be7e026a03dc8953d09112b81

**Comment by azuisleet** [comment]
2.4.4 is now available https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.4.4

Please give it a try.

**Comment by willemml** [comment]
That works perfectly, thank you for the quick fix!
