### ISSUE TITLE
Unhandled exception. System.ArgumentException: 314C9ECF5F92A8328666776D7BC8C623 is not a valid value for UInt64. (Parameter 'value')

### ISSUE THREAD

**Issue by gac123** [SteamRE/DepotDownloader#482]
### What did you expect to happen?

download older version of steamvr with either commands

dotnet DepotDownloader.dll -app 250820 -depot 250821 -manifest 314C9ECF5F92A8328666776D7BC8C623

DepotDownloader.exe -app 250820 -depot 250821 -manifest 314C9ECF5F92A8328666776D7BC8C623

### Instead of that, what actually happened?

Unhandled exception. System.ArgumentException: 314C9ECF5F92A8328666776D7BC8C623 is not a valid value for UInt64. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.UInt64.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.UInt64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at DepotDownloader.Program.GetParameterList[T](String[] args, String param) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 352
   at DepotDownloader.Program.MainAsync(String[] args) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 215
   at DepotDownloader.Program.Main(String[] args) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 17

### Which operating system are you running on?

Windows

### Version

latest as of 9th march 2024

### Relevant log output

```shell
Unhandled exception. System.ArgumentException: 314C9ECF5F92A8328666776D7BC8C623 is not a valid value for UInt64. (Parameter 'value')
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.UInt64.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.ComponentModel.UInt64Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at DepotDownloader.Program.GetParameterList[T](String[] args, String param) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 352
   at DepotDownloader.Program.MainAsync(String[] args) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 215
   at DepotDownloader.Program.Main(String[] args) in D:\a\DepotDownloader\DepotDownloader\DepotDownloader\Program.cs:line 17
```

**Comment by NagaseYami** [comment]
Wrong Manifest ID
https://steamdb.info/depot/250821/manifests/

**Comment by yaakov-h** [comment]
Where did you get that manifest ID from?

**Comment by NagaseYami** [comment]
>Wrong Manifest ID
https://steamdb.info/depot/250821/manifests/

> Where did you get that manifest ID from?

Strange question. Does your eye have an automatic filter that blocks URLs?

**Comment by yaakov-h** [comment]
Not you, the OP. Your post did not contain a manifest ID so it could not have been addressed to you.

**Comment by gac123** [comment]
> Where did you get that manifest ID from?

steamvr depots, tried different ones; depots 250821, 250824, 250827 (the only one that worked with steamcmd)
https://steamdb.info/app/250820/depots/?branch=v1.27.5

**Comment by NagaseYami** [comment]
> Not you, the OP. Your post did not contain a manifest ID so it could not have been addressed to you.

Srroy, my bad.

**Comment by yaakov-h** [comment]
@gac123 those are marked as **encrypted** manifest IDs. you need to decrypt one before you can download it - this is not something trivially doable.
