### ISSUE TITLE
DepotDownloader not remembering password again (despite -remember-password)

### ISSUE THREAD

**Issue by ZetaTwo** [SteamRE/DepotDownloader#539]
### What did you expect to happen?

Running the following command twice, I expect to only be asked for password the first time:
```
./DepotDownloader -app 813780 -depot 813781 -filelist files.txt -os windows -username <READACTED> -remember-password -dir "downloads/" -manifest 8448015185409384747 
```

### Instead of that, what actually happened?

Instead I am asked for a password (and auth code) every time

The symptoms seem to be the same as in #397. I have not dug deeper to find a root cause in the code.

### Which operating system are you running on?

Linux

### Version

DepotDownloader v2.7.1+907b3360ccec0bace6810bca32c8ff0b74ad3273, Runtime: .NET 8.0.8 on Ubuntu 24.04.1 LTS

### Command

./DepotDownloader -app 813780 -depot 813781 -filelist files.txt -os windows -username <READACTED> -remember-password -dir "downloads/" -manifest 8448015185409384747 

### Relevant log output

```shell
DepotDownloader v2.7.1+907b3360ccec0bace6810bca32c8ff0b74ad3273
Runtime: .NET 8.0.8 on Ubuntu 24.04.1 LTS
Using filelist: 'files.txt'.
Enter account password for "REDACTED": ********************
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
11:27:29.7082762  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /ISteamDirectory/GetCMList/v1/?format=vdf&cellid=0, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
11:27:29.7313671  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
11:27:30.2061397  System.Net.NameResolution.ResolutionStop()
11:27:30.2108849  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,2,16,174,204,0,0,0,0,0,0,0,0})
11:27:30.2203771  System.Net.Sockets.ConnectStop()
11:27:30.2233909  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
11:27:30.3944316  System.Net.Security.HandshakeStop(protocol: 12288)
11:27:30.3975871  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 0, scheme: https, host: api.steampowered.com, port: 443, remoteAddress: 2.16.174.204)
11:27:30.3991754  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 675.9574, versionMajor: 1, versionMinor: 1)
11:27:30.4011667  System.Net.Http.RequestHeadersStart(connectionId: 0)
11:27:30.4018943  System.Net.Http.RequestHeadersStop()
11:27:30.7307671  System.Net.Http.ResponseHeadersStart()
11:27:30.7342506  System.Net.Http.ResponseHeadersStop(statusCode: 200)
11:27:30.7359140  System.Net.Http.ResponseContentStart()
11:27:30.7371143  System.Net.Http.ResponseContentStop()
11:27:30.7371799  System.Net.Http.RequestStop(statusCode: 200)
11:27:30.7415412  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 0)
[ServerList] Resolved 178 servers
[ServerList] Next server candidate: 162.254.197.38:27017 (Tcp)
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Connecting to 162.254.197.38:27017...
11:27:30.7604468  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{105,137,162,254,197,38,0,0,0,0,0,0,0,0})
11:27:35.7681075  System.Net.Sockets.ConnectFailed(error: 10038, exceptionMessage: )
11:27:35.7694091  System.Net.Sockets.ConnectStop()
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Exception while connecting to 162.254.197.38:27017: System.Net.Sockets.SocketException (88): Socket operation on non-socket 162.254.197.38:27017
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at SteamKit2.TcpConnection.TryConnect(Int32 timeout)
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Failed connecting to 162.254.197.38:27017
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = False, bExpectingDisconnectRemote = False
Connection to Steam failed. Trying again
[ServerList] Next server candidate: 155.133.226.75:27017 (Tcp)
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Connecting to 155.133.226.75:27017...
11:27:36.8080189  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{105,137,155,133,226,75,0,0,0,0,0,0,0,0})
11:27:41.8092833  System.Net.Sockets.ConnectFailed(error: 10038, exceptionMessage: )
11:27:41.8094706  System.Net.Sockets.ConnectStop()
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Exception while connecting to 155.133.226.75:27017: System.Net.Sockets.SocketException (88): Socket operation on non-socket 155.133.226.75:27017
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at SteamKit2.TcpConnection.TryConnect(Int32 timeout)
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Failed connecting to 155.133.226.75:27017
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = False, bExpectingDisconnectRemote = False
Connection to Steam failed. Trying again
[ServerList] Next server candidate: 155.133.252.40:27017 (Tcp)
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Connecting to 155.133.252.40:27017...
11:27:43.8142876  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{105,137,155,133,252,40,0,0,0,0,0,0,0,0})
11:27:43.8192851  System.Net.Sockets.ConnectStop()
[e9573d06e72a4caea1c65213a3d88bd4/TcpConnection] Connected to 155.133.252.40:27017
[e9573d06e72a4caea1c65213a3d88bd4/EnvelopeEncryptedConnection] Got encryption request. Universe: Public Protocol ver: 1
[e9573d06e72a4caea1c65213a3d88bd4/EnvelopeEncryptedConnection] Encryption result: OK
 Done!
Logging 'REDACTED' into Steam3...
STEAM GUARD! Please enter the auth code sent to the email at REDACTED: G9VJ8
 Done!
Using Steam3 suggested CellID: 176
Got 3 licenses for account!
Got AppInfo for 813780
Using app branch: 'public'.
Got depot key for 813781 result: OK
Processing depot 813781
Already have manifest 8448015185409384747 for depot 813781.
Manifest 8448015185409384747 (10/22/2018 5:35:38 AM)
Downloading depot 813781
Depot 813781 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = True, bExpectingDisconnectRemote = False
Disconnected from Steam
```

### Additional Information

Thanks for building this fantastic tool! Much love!
I'm using the pre-built linux amd64 binary from the releases page.

**Comment by xPaw** [comment]
I can't repro this. It will only ask for password if it has no access token stored in the config file. If it does get removed it would have said something about failing to login first and then shutdown, which your current log wouldn't show.

**Comment by 7H3LaughingMan** [comment]
I just wanted to comment that I was having the same issue and it was resolved by double checking the capitalization in my username as well. From my understanding the username isn't case-sensitive and it always lowercase. I don't know if you can add something to make sure the username is converted to lowercase or just add a note in the FAQ to double check the capitalization in your username.
