### ISSUE TITLE
recent updates fail to connect at all

### ISSUE THREAD

**Issue by modderchris** [SteamRE/DepotDownloader#548]
### What did you expect to happen?

for my script with my username, password, and saved steam gaurd credentials that worked before to fully redownload skyrim SE 353

### Instead of that, what actually happened?

when the script runs it unpredictably fails to connect randomly, sometimes it works, sometimes it gets stuck "retrying" until the depot fully aborts with no warning

### Which operating system are you running on?

Windows

### Version

multiple including latest of this day

### Command

depotdownloader -app 489830 -depot 489831 -manifest 7089166303853251347 -user %user% -password %pass% -remember-password 

### Relevant log output

```shell
DepotDownloader v2.7.2+5a695e6dd13db74a286659d129784a872a5648b8
Runtime: .NET 8.0.8 on Microsoft Windows 10.0.19045
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
20:04:46.3685189  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /ISteamDirectory/GetCMListForConnect/v1/?format=vdf&cellid=0, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
20:04:46.4059982  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
20:04:46.4388817  System.Net.NameResolution.ResolutionStop()
20:04:46.4401647  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,23,47,27,74,0,0,0,0,0,0,0,0})
20:04:46.4752254  System.Net.Sockets.ConnectStop()
20:04:46.4779976  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
20:04:46.5749919  System.Net.Security.HandshakeStop(protocol: 3072)
20:04:46.5777685  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 0, scheme: https, host: api.steampowered.com, port: 443, remoteAddress: 23.47.27.74)
20:04:46.5787518  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 179.5749, versionMajor: 1, versionMinor: 1)
20:04:46.5807523  System.Net.Http.RequestHeadersStart(connectionId: 0)
20:04:46.5811476  System.Net.Http.RequestHeadersStop()
20:04:46.7807476  System.Net.Http.ResponseHeadersStart()
20:04:46.7815639  System.Net.Http.ResponseHeadersStop(statusCode: 200)
20:04:46.7827168  System.Net.Http.ResponseContentStart()
20:04:46.8172686  System.Net.Http.ResponseContentStop()
20:04:46.8173256  System.Net.Http.RequestStop(statusCode: 200)
20:04:46.8230035  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 0)
[ServerList] Resolved 160 servers
[ServerList] Next server candidate: Unspecified/ext2-par1.steamserver.net:27020 (WebSocket)
20:04:46.8390297  System.Net.Http.RequestStart(scheme: wss, host: ext2-par1.steamserver.net, port: 27020, pathAndQuery: /cmsocket/, versionMajor: 1, versionMinor: 1, versionPolicy: 2)
20:04:46.8395576  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: ext2-par1.steamserver.net)
20:04:46.8629604  System.Net.NameResolution.ResolutionStop()
20:04:46.8633095  System.Net.Sockets.ConnectStart(address: InterNetworkV6:28:{105,140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,185,25,182,52,0,0,0,0})
20:04:46.9905290  System.Net.Sockets.ConnectStop()
20:04:46.9908069  System.Net.Security.HandshakeStart(isServer: False, targetHost: ext2-par1.steamserver.net)
20:04:47.2556965  System.Net.Security.HandshakeStop(protocol: 3072)
20:04:47.2599201  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 1, scheme: https, host: ext2-par1.steamserver.net, port: 27020, remoteAddress: ::ffff:185.25.182.52)
20:04:47.2600986  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 420.7867, versionMajor: 1, versionMinor: 1)
20:04:47.2601752  System.Net.Http.RequestHeadersStart(connectionId: 1)
20:04:47.2602145  System.Net.Http.RequestHeadersStop()
20:04:47.3933501  System.Net.Http.ResponseHeadersStart()
20:04:47.3934252  System.Net.Http.ResponseHeadersStop(statusCode: 101)
20:04:47.3939161  System.Net.Http.RequestStop(statusCode: 101)
[01b7dd8cbe724d47bee8b659addf43b6/WebSocketContext] Connected to wss://ext2-par1.steamserver.net:27020/cmsocket/
 Done!
Logging 'sniperchris1024' into Steam3...
 Done!
Using Steam3 suggested CellID: 83
Got 77 licenses for account!
Got AppInfo for 489830
Using app branch: 'public'.
Got depot key for 489831 result: OK
Processing depot 489831
Already have manifest 7089166303853251347 for depot 489831.
Manifest 7089166303853251347 (12/15/2021 11:17:29 PM)
Downloading depot 489831
 17.06% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Meshes0.bsa
 17.26% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Video\BGS_Logo.bik
 20.29% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Misc.bsa
 43.05% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Sounds.bsa
 48.66% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Meshes1.bsa
 49.62% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Animations.bsa
 55.21% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE001-Fish.bsa
 81.95% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Voices_en0.bsa
 81.97% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE001-Fish.esm
 81.99% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE025-AdvDSGS.esm
 83.64% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE037-Curios.bsa
 83.64% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE037-Curios.esl
 83.64% T:\GameInstalls\steamapps\common\\SkyrimSE\installscript.vdf
 83.64% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccQDRSSE001-SurvivalMode.esl
 99.81% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccBGSSSE025-AdvDSGS.bsa
100.00% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\ccQDRSSE001-SurvivalMode.bsa
Depot 489831 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
20:04:50.3762576  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 1)
[01b7dd8cbe724d47bee8b659addf43b6/WebSocketContext] Exception reading from websocket: System.Threading.Tasks.TaskCanceledException - The operation was canceled.
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = True, bExpectingDisconnectRemote = False
Disconnected from Steam
DepotDownloader v2.7.2+5a695e6dd13db74a286659d129784a872a5648b8
Runtime: .NET 8.0.8 on Microsoft Windows 10.0.19045
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
20:04:50.5827106  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /ISteamDirectory/GetCMListForConnect/v1/?format=vdf&cellid=0, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
20:04:50.6204086  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
20:04:50.6478328  System.Net.NameResolution.ResolutionStop()
20:04:50.6491101  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,23,47,27,74,0,0,0,0,0,0,0,0})
20:04:50.6816186  System.Net.Sockets.ConnectStop()
20:04:50.6841868  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
20:04:50.7916730  System.Net.Security.HandshakeStop(protocol: 3072)
20:04:50.7943193  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 0, scheme: https, host: api.steampowered.com, port: 443, remoteAddress: 23.47.27.74)
20:04:50.7953025  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 181.6507, versionMajor: 1, versionMinor: 1)
20:04:50.7973212  System.Net.Http.RequestHeadersStart(connectionId: 0)
20:04:50.7977479  System.Net.Http.RequestHeadersStop()
20:04:51.0459483  System.Net.Http.ResponseHeadersStart()
20:04:51.0466591  System.Net.Http.ResponseHeadersStop(statusCode: 200)
20:04:51.0478923  System.Net.Http.ResponseContentStart()
20:04:51.0857406  System.Net.Http.ResponseContentStop()
20:04:51.0858218  System.Net.Http.RequestStop(statusCode: 200)
20:04:51.0915583  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 0)
[ServerList] Resolved 160 servers
[ServerList] Next server candidate: Unspecified/ext1-gru1.steamserver.net:27031 (WebSocket)
20:04:51.1080370  System.Net.Http.RequestStart(scheme: wss, host: ext1-gru1.steamserver.net, port: 27031, pathAndQuery: /cmsocket/, versionMajor: 1, versionMinor: 1, versionPolicy: 2)
20:04:51.1085476  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: ext1-gru1.steamserver.net)
20:04:51.1317583  System.Net.NameResolution.ResolutionStop()
20:04:51.1321005  System.Net.Sockets.ConnectStart(address: InterNetworkV6:28:{105,151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,155,133,227,34,0,0,0,0})
20:04:51.2996700  System.Net.Sockets.ConnectStop()
20:04:51.2998829  System.Net.Security.HandshakeStart(isServer: False, targetHost: ext1-gru1.steamserver.net)
20:04:51.6539759  System.Net.Security.HandshakeStop(protocol: 3072)
20:04:51.6583906  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 1, scheme: https, host: ext1-gru1.steamserver.net, port: 27031, remoteAddress: ::ffff:155.133.227.34)
20:04:51.6585103  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 550.1937, versionMajor: 1, versionMinor: 1)
20:04:51.6585602  System.Net.Http.RequestHeadersStart(connectionId: 1)
20:04:51.6585947  System.Net.Http.RequestHeadersStop()
20:04:51.8244526  System.Net.Http.ResponseHeadersStart()
20:04:51.8245156  System.Net.Http.ResponseHeadersStop(statusCode: 101)
20:04:51.8249552  System.Net.Http.RequestStop(statusCode: 101)
[b17e5ecd9e0149b38e519759ca94e24c/WebSocketContext] Connected to wss://ext1-gru1.steamserver.net:27031/cmsocket/
 Done!
Logging 'sniperchris1024' into Steam3...
 Done!
Using Steam3 suggested CellID: 83
Got 77 licenses for account!
Got AppInfo for 489830
Using app branch: 'public'.
Got depot key for 489832 result: OK
Processing depot 489832
Already have manifest 1476684358338706955 for depot 489832.
Manifest 1476684358338706955 (12/15/2021 11:17:49 PM)
Downloading depot 489832
 17.74% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures1.bsa
 18.04% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Dawnguard.esm
 25.69% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures0.bsa
 41.49% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures2.bsa
 42.25% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Dragonborn.esm
 43.17% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Interface.bsa
 43.22% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\HearthFires.esm
 44.01% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Shaders.bsa
 60.45% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures3.bsa
 75.30% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures4.bsa
 84.79% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures5.bsa
 93.02% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures7.bsa
 95.95% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim.esm
 97.20% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures6.bsa
 97.42% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Update.esm
 97.42% T:\GameInstalls\steamapps\common\\SkyrimSE\Medium.ini
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\Data\Skyrim - Textures8.bsa
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\Low.ini
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\Ultra.ini
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\Skyrim.ccc
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\High.ini
 99.94% T:\GameInstalls\steamapps\common\\SkyrimSE\Skyrim_Default.ini
 99.99% T:\GameInstalls\steamapps\common\\SkyrimSE\SkyrimSELauncher.exe
 99.99% T:\GameInstalls\steamapps\common\\SkyrimSE\Skyrim\SkyrimPrefs.ini
100.00% T:\GameInstalls\steamapps\common\\SkyrimSE\steam_api64.dll
100.00% T:\GameInstalls\steamapps\common\\SkyrimSE\bink2w64.dll
Depot 489832 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
20:04:54.9534808  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 1)
[b17e5ecd9e0149b38e519759ca94e24c/WebSocketContext] Exception reading from websocket: System.Threading.Tasks.TaskCanceledException - The operation was canceled.
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = True, bExpectingDisconnectRemote = False
Disconnected from Steam
DepotDownloader v2.7.2+5a695e6dd13db74a286659d129784a872a5648b8
Runtime: .NET 8.0.8 on Microsoft Windows 10.0.19045
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
20:04:55.1668735  System.Net.Http.RequestStart(scheme: https, host: api.steampowered.com, port: 443, pathAndQuery: /ISteamDirectory/GetCMListForConnect/v1/?format=vdf&cellid=0, versionMajor: 1, versionMinor: 1, versionPolicy: 0)
20:04:55.2100278  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: api.steampowered.com)
20:04:55.2141629  System.Net.NameResolution.ResolutionStop()
20:04:55.2154794  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{1,187,23,47,27,74,0,0,0,0,0,0,0,0})
20:04:55.2500963  System.Net.Sockets.ConnectStop()
20:04:55.2526848  System.Net.Security.HandshakeStart(isServer: False, targetHost: api.steampowered.com)
20:04:55.3457011  System.Net.Security.HandshakeStop(protocol: 3072)
20:04:55.3485216  System.Net.Http.ConnectionEstablished(versionMajor: 1, versionMinor: 1, connectionId: 0, scheme: https, host: api.steampowered.com, port: 443, remoteAddress: 23.47.27.74)
20:04:55.3495136  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 146.9309, versionMajor: 1, versionMinor: 1)
20:04:55.3516360  System.Net.Http.RequestHeadersStart(connectionId: 0)
20:04:55.3520362  System.Net.Http.RequestHeadersStop()
20:04:55.5478266  System.Net.Http.ResponseHeadersStart()
20:04:55.5485548  System.Net.Http.ResponseHeadersStop(statusCode: 200)
20:04:55.5495796  System.Net.Http.ResponseContentStart()
20:04:55.5824407  System.Net.Http.ResponseContentStop()
20:04:55.5824884  System.Net.Http.RequestStop(statusCode: 200)
20:04:55.5889033  System.Net.Http.ConnectionClosed(versionMajor: 1, versionMinor: 1, connectionId: 0)
[ServerList] Resolved 160 servers
[ServerList] Next server candidate: Unspecified/cmp2-atl3.steamserver.net:443 (WebSocket)
20:04:55.6054412  System.Net.Http.RequestStart(scheme: wss, host: cmp2-atl3.steamserver.net, port: 443, pathAndQuery: /cmsocket/, versionMajor: 1, versionMinor: 1, versionPolicy: 2)
20:04:55.6060706  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: cmp2-atl3.steamserver.net)
20:04:55.6066298  System.Net.NameResolution.ResolutionStop()
20:04:55.6069004  System.Net.Sockets.ConnectStart(address: InterNetworkV6:28:{1,187,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,162,254,199,184,0,0,0,0})
20:04:55.6610056  System.Net.Sockets.ConnectStop()
20:04:55.6612224  System.Net.Security.HandshakeStart(isServer: False, targetHost: cmp2-atl3.steamserver.net)
20:04:55.7158077  System.Net.Security.HandshakeFailed(isServer: False, elapsedMilliseconds: 54.5428, exceptionMessage: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.)
20:04:55.7158819  System.Net.Security.HandshakeStop(protocol: 0)
20:04:55.7168910  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 111.1277, versionMajor: 1, versionMinor: 1)
20:04:55.7174145  System.Net.Http.RequestFailed(exceptionMessage: The SSL connection could not be established, see inner exception.)
20:04:55.7239967  System.Net.Http.RequestFailedDetailed(exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(Boolean isAsync, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken))
20:04:55.7241099  System.Net.Http.RequestStop(statusCode: -1)
[a3f97243601f44788a1cae71704509ed/WebSocketContext] Exception connecting websocket: System.Net.WebSockets.WebSocketException - Unable to connect to the remote server
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = False, bExpectingDisconnectRemote = False
Connection to Steam failed. Trying again
[ServerList] Next server candidate: Unspecified/cmp1-atl3.steamserver.net:443 (WebSocket)
20:04:56.7393000  System.Net.Http.RequestStart(scheme: wss, host: cmp1-atl3.steamserver.net, port: 443, pathAndQuery: /cmsocket/, versionMajor: 1, versionMinor: 1, versionPolicy: 2)
20:04:56.7396041  System.Net.NameResolution.ResolutionStart(hostNameOrAddress: cmp1-atl3.steamserver.net)
20:04:56.7400266  System.Net.NameResolution.ResolutionStop()
20:04:56.7402426  System.Net.Sockets.ConnectStart(address: InterNetworkV6:28:{1,187,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,162,254,199,165,0,0,0,0})
20:04:56.7887124  System.Net.Sockets.ConnectStop()
20:04:56.7888784  System.Net.Security.HandshakeStart(isServer: False, targetHost: cmp1-atl3.steamserver.net)
20:04:56.8412794  System.Net.Security.HandshakeFailed(isServer: False, elapsedMilliseconds: 52.2849, exceptionMessage: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.)
20:04:56.8413504  System.Net.Security.HandshakeStop(protocol: 0)
20:04:56.8417945  System.Net.Http.RequestLeftQueue(timeOnQueueMilliseconds: 102.3744, versionMajor: 1, versionMinor: 1)
20:04:56.8418990  System.Net.Http.RequestFailed(exceptionMessage: The SSL connection could not be established, see inner exception.)
20:04:56.8425479  System.Net.Http.RequestFailedDetailed(exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(Boolean isAsync, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionWithTelemetryAsync(HttpRequestMessage request, HttpConnectionPool pool, Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken))
20:04:56.8426330  System.Net.Http.RequestStop(statusCode: -1)
[a3f97243601f44788a1cae71704509ed/WebSocketContext] Exception connecting websocket: System.Net.WebSockets.WebSocketException - Unable to connect to the remote server
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = False, bExpectingDisconnectRemote = False
Connection to Steam failed. Trying again
[ServerList] Next server candidate: Unspecified/162.254.199.163:27017 (Tcp)
[a3f97243601f44788a1cae71704509ed/TcpConnection] Connecting to Unspecified/162.254.199.163:27017...
20:04:58.8488532  System.Net.Sockets.ConnectStart(address: InterNetwork:16:{105,137,162,254,199,163,0,0,0,0,0,0,0,0})
20:04:58.8953783  System.Net.Sockets.ConnectStop()
[a3f97243601f44788a1cae71704509ed/TcpConnection] Connected to Unspecified/162.254.199.163:27017
[a3f97243601f44788a1cae71704509ed/EnvelopeEncryptedConnection] Got encryption request. Universe: Public Protocol ver: 1
[a3f97243601f44788a1cae71704509ed/EnvelopeEncryptedConnection] Encryption result: OK
 Done!
Logging 'sniperchris1024' into Steam3...
 Done!
Using Steam3 suggested CellID: 83
Got 77 licenses for account!
Got AppInfo for 489830
Using app branch: 'public'.
Got depot key for 489833 result: OK
Processing depot 489833
Already have manifest 4570833277049890269 for depot 489833.
Manifest 4570833277049890269 (12/15/2021 11:18:01 PM)
Downloading depot 489833
100.00% T:\GameInstalls\steamapps\common\\SkyrimSE\SkyrimSE.exe
Depot 489833 - Downloaded 0 bytes (0 bytes uncompressed)
Total downloaded: 0 bytes (0 bytes uncompressed) from 1 depots
[Steam3Session] Disconnected: bIsConnectionRecovery = False, UserInitiated = True, bExpectingDisconnectRemote = False
Disconnected from Steam
done downgrading and verifying SkyrimSE

Waiting for 10 seconds, press a key to continue ... 9 8 7 6 5 4 3 2 1 0
Press any key to continue . . . 
Terminate batch job (Y/N)?
```

### Additional Information

it simply randomly fails, ping was tested, servers are working
script code minus the config file that sets game dir and depotdownloader install folder which contains the password in plaintext for sharing a sanitized script: 
`@echo off
call %cd%\login.bat
%scriptdir:~0,2%
set scriptdirshort=%scriptdir:~2,255%
cd %scriptdirshort%
%depotdir%depotdownloader -app 489830 -depot 489831 -manifest 7089166303853251347 -user %user% -password %pass% -remember-password -dir "%libdir%\SkyrimSE"
%depotdir%depotdownloader -app 489830 -depot 489832 -manifest 1476684358338706955 -user %user% -password %pass% -remember-password -dir "%libdir%\SkyrimSE"
%depotdir%depotdownloader -app 489830 -depot 489833 -manifest 4570833277049890269 -user %user% -password %pass% -remember-password -dir "%libdir%\SkyrimSE"
echo done downgrading and verifying SkyrimSE
timeout`
libdir points to game folder and depotdir points to the install folder of depotdownloader, the login.bat simply has the instructions for adding your password and the called strings to store them in variables
it worked perfectly every time many times about a year or 2 ago un multiple versions, is this a steam issue or depotdownloader?

**Comment by modderchris** [comment]
as you might see it actually worked this time to complete all 3 major commands with only a single blip in the initial handshake, and a TLS error was the cause, I am no windows coder but I am 100% sure the end-user is not expected to update obscure TLS version data, and windows 11 is still too unstable to trust so if it is a windows 10 bug then microsoft needs to be forced to fix it
