### ISSUE TITLE
Crash when downloading from app 346680

### ISSUE THREAD

**Issue by GoD-Tony** [SteamRE/DepotDownloader#6]
Getting this crash when downloading from app 346680 - Black Mesa Dedicated Server. Let me know if you need more info.

    Using filelist: './filelist.txt'.
    No username given. Using anonymous account with dedicated server subscription.
    Connecting to Steam3... Done!
    Logging anonymously into Steam3... Done!
    Using Steam3 suggested CellID: 41
    Got AppInfo for 346680
    Got depot key for 346682 result: OK
    Got depot key for 346683 result: OK
    Got depot key for 346681 result: OK
    Insufficient privileges to get access token for app 221140
    Got AppInfo for 221140

    Unhandled Exception: System.NullReferenceException: Object reference not set to
    an instance of an object.
       at DepotDownloader.ContentDownloader.GetSteam3DepotManifest(UInt32 depotId, UInt32 appId, String branch)
       at DepotDownloader.ContentDownloader.GetSteam3DepotManifest(UInt32 depotId, UInt32 appId, String branch)
       at DepotDownloader.ContentDownloader.GetDepotInfo(UInt32 depotId, UInt32 appId, String branch)
       at DepotDownloader.ContentDownloader.DownloadApp(UInt32 appId, UInt32 depotId, String branch)
       at DepotDownloader.Program.Main(String[] args)

**Comment by azuisleet** [comment]
I've added a bypass in 52d45da that will allow it to continue with the depot manifest for the current appid if it can't retrieve depotfromapp.

**Comment by GoD-Tony** [comment]
Working now, thanks!
