### ISSUE TITLE
Prebuilt binary exits with error when run without console

### ISSUE THREAD

**Issue by eroen** [SteamRE/DepotDownloader#61]
I would like to run DepotDownloader in a script without console (to use it with Gentoo's package manager Portage). Unfortunately, the prebuilt binary (version 2.3.1) exits with an error if you run it with input redirected. While the files get downloaded, this makes it hard to differentiate between a successful run and a legitimate failure.

I have not been able to reproduce this in my own builds (using Dotnetcore SDK 2.2.402 on Linux), only with the binary downloaded from the Releases page on Github.

```
eroen@occam ~ $ echo -n | dotnet .../DepotDownloader.dll -username 6SuVT -password XXX -app 307210
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
[ServerList] Resolved 200 servers
[ServerList] Next server candidiate: 162.254.198.130:27018 (Tcp)
[TcpConnection] Connecting to 162.254.198.130:27018...
[TcpConnection] Connected to 162.254.198.130:27018
[EnvelopeEncryptedConnection] Got encryption request. Universe: Public Protocol ver: 1
[EnvelopeEncryptedConnection] Encryption result: OK
...
100.00% depots/307214/700786/res/sounds/music/WFF Boss.ogg
Depot 307214 - Downloaded 244430640 bytes (263812758 bytes uncompressed)
Total downloaded: 244430640 bytes (263809856 bytes uncompressed) from 1 depots
[CMClient] Sent -> EMsg: ClientLogOff (Proto: True)
Disconnected from Steam

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at DepotDownloader.Program.MainAsync(String[] args)
   at DepotDownloader.Program.Main(String[] args)
Aborted
eroen@occam ~ $ echo $?
134
```

**Comment by azuisleet** [comment]
Yes, it looks like the built binary included some extra debug lines, including that Console.ReadKey at the end of the loop.

I have uploaded a correct binary as depotdownloader-2.3.1-hotfix1
