### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by fireundubh** [SteamRE/DepotDownloader#7]
While downloading:

    Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.OverflowException: Arithmetic operation resulted in an overflow.
      at System.Linq.Enumerable.Sum(IEnumerable`1 source)
      at DepotDownloader.ContentDownloader.<>c__DisplayClass28.<DownloadSteam3>b__1c(FileData file)
      at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
      at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
      at System.Linq.Parallel.SpoolingTaskBase.Work()
      at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
      at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
      at System.Threading.Tasks.Task.InnerInvoke()
      at System.Threading.Tasks.Task.Execute()
      --- End of inner exception stack trace ---
      at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
      at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
      at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
      at System.Linq.Parallel.MergeExecutor`1.Execute()
      at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
      at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
      at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
      at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
      at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
      at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
      at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
      at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
      at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
      at DepotDownloader.ContentDownloader.DownloadSteam3(List`1 depots)
      at DepotDownloader.ContentDownloader.DownloadApp(UInt32 appId, UInt32 depotId, String branch, Boolean forceDepot)
      at DepotDownloader.Program.Main(String[] args)

**Comment by azuisleet** [comment]
I believe this is a result of an overflow when calculating the size when diffing a file. Please try 5cf8c66

**Comment by fireundubh** [comment]
Your fix resolved the issue. The download was able to complete without crashing.
