### ISSUE TITLE
Can not download Depot

### ISSUE THREAD

**Issue by GoldSourceTest** [SteamRE/DepotDownloader#89]
```
Connecting to Steam3...[ServerList] Resolving server list
[ServerList] Server list provider had no entries, will query SteamDirectory
[ServerList] Resolved 200 servers
[ServerList] Next server candidiate: 153.254.86.181:27017 (Tcp)
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Connecting to 153.254.86.181:27
017...
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Connected to 153.254.86.181:270
17
[10025ffd6fd546e08f8e5df2c95c15c3/EnvelopeEncryptedConnection] Rejected EMsg: Ch
annelEncryptRequest during channel setup
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Socket exception occurred while
 reading packet: System.IO.IOException: Connection lost while reading packet hea
der. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the s
tream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\Ste
amKit2\Networking\Steam3\TcpConnection.cs:line 284
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\Ste
amKit2\Networking\Steam3\TcpConnection.cs:line 289
   at SteamKit2.TcpConnection.NetLoop() in C:\Projects\SteamKit\SteamKit2\SteamK
it2\Networking\Steam3\TcpConnection.cs:line 247
Connection to Steam failed. Trying again
[ServerList] Next server candidiate: 153.254.86.179:27019 (Tcp)
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Connecting to 153.254.86.179:27
019...
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Connected to 153.254.86.179:270
19
[10025ffd6fd546e08f8e5df2c95c15c3/EnvelopeEncryptedConnection] Rejected EMsg: Ch
annelEncryptRequest during channel setup
Timeout connecting to Steam3.
Unable to get steam3 credentials.
Error: InitializeSteam failed
[10025ffd6fd546e08f8e5df2c95c15c3/TcpConnection] Socket exception occurred while
 reading packet: System.IO.IOException: Connection lost while reading packet hea
der. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the s
tream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\Ste
amKit2\Networking\Steam3\TcpConnection.cs:line 284
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket() in C:\Projects\SteamKit\SteamKit2\Ste
amKit2\Networking\Steam3\TcpConnection.cs:line 289
   at SteamKit2.TcpConnection.NetLoop() in C:\Projects\SteamKit\SteamKit2\SteamK
it2\Networking\Steam3\TcpConnection.cs:line 247
```

**Comment by azuisleet** [comment]
Please check if you have any firewalls setup. You will need to allow DepotDownloader to access the internet.

**Comment by Jarfeh** [comment]
How would you allow access to an app that is not an exe?
